version: "2"
linters:
  default: none
  enable:
    - containedctx
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gosec
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unparam
    - unused
    - usestdlibvars
  settings:
    exhaustruct:
      exclude:
        - github\.com/google/go-github/v65/github\.CheckRunOutput
        - github\.com/google/go-github/v65/github\.ListCheckRunsOptions
        - github\.com/google/go-github/v65/github\.ListOptions
        - github\.com/golang-jwt/jwt\.StandardClaims
        - net/http\.Client
    gomoddirectives:
      replace-allow-list:
        - launchpad.net/gocheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
