FROM wptd-base

ADD . "${WPTD_PATH}"

# Ensure Google Cloud Platform tools are installed
RUN gcloud components install \
    app-engine-go \
    bq \
    core \
    gsutil \
    app-engine-python

# Expose Sauce Connect port
EXPOSE 4445
