FROM wptd-base

USER root

# Install inotify-tools for dev server scripts
RUN apt-get install --assume-yes --no-install-suggests \
    --no-install-recommends \
    inotify-tools

# Ensure Google Cloud Platform tools are installed
RUN gcloud components install \
    app-engine-go \
    bq \
    core \
    gsutil \
    app-engine-python

# Put wpt.fyi code in GOPATH
RUN mkdir -p "${GOPATH}/src/github.com/web-platform-tests"
RUN ln -s "${WPTD_PATH}" "${GOPATH}/src/github.com/web-platform-tests/wpt.fyi"

# Drop dev environment into source path
WORKDIR "${WPTD_PATH}"
