# Copyright 2017 The WPT Dashboard Project. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

runtime: custom
env: flex
instance_class: F4_1G

inbound_services:
- warmup

default_expiration: "1d"

vpc_access_connector:
  name: projects/wptdashboard/locations/us-central1/connectors/appengine-connector

env_variables:
  REDISHOST: "10.171.142.203"
  REDISPORT: "6379"

