# Copyright 2017 The WPT Dashboard Project. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

runtime: custom
env: flex
resources:
  cpu: 2
  memory_gb: 4

automatic_scaling:
  min_num_instances: 4
  max_num_instances: 20
  cool_down_period_sec: 180

inbound_services:
- warmup

default_expiration: "1d"

vpc_access_connector:
  name: projects/wptdashboard/locations/us-central1/connectors/appengine-connector

liveness_check:
  path: "/_ah/liveness_check"

readiness_check:
  path: "/_ah/readiness_check"
  app_start_timeout_sec: 300
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 4
  success_threshold: 2

env_variables:
  REDISHOST: "10.171.142.203"
  REDISPORT: "6379"

