// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/web-platform-tests/wpt.fyi/api/query/cache/backfill (interfaces: RunFetcher)

// Package mock_backfill is a generated GoMock package.
package mock_backfill

import (
	gomock "github.com/golang/mock/gomock"
	shared "github.com/web-platform-tests/wpt.fyi/shared"
	reflect "reflect"
)

// MockRunFetcher is a mock of RunFetcher interface
type MockRunFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockRunFetcherMockRecorder
}

// MockRunFetcherMockRecorder is the mock recorder for MockRunFetcher
type MockRunFetcherMockRecorder struct {
	mock *MockRunFetcher
}

// NewMockRunFetcher creates a new mock instance
func NewMockRunFetcher(ctrl *gomock.Controller) *MockRunFetcher {
	mock := &MockRunFetcher{ctrl: ctrl}
	mock.recorder = &MockRunFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRunFetcher) EXPECT() *MockRunFetcherMockRecorder {
	return m.recorder
}

// FetchRuns mocks base method
func (m *MockRunFetcher) FetchRuns(arg0 int) (shared.TestRunsByProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRuns", arg0)
	ret0, _ := ret[0].(shared.TestRunsByProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRuns indicates an expected call of FetchRuns
func (mr *MockRunFetcherMockRecorder) FetchRuns(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRuns", reflect.TypeOf((*MockRunFetcher)(nil).FetchRuns), arg0)
}
