// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/web-platform-tests/wpt.fyi/shared (interfaces: FetchFeatureInterop)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -destination sharedtest/fetch_feature_interop_mock.go -package sharedtest github.com/web-platform-tests/wpt.fyi/shared FetchFeatureInterop
//

// Package sharedtest is a generated GoMock package.
package sharedtest

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFetchFeatureInterop is a mock of FetchFeatureInterop interface.
type MockFetchFeatureInterop struct {
	ctrl     *gomock.Controller
	recorder *MockFetchFeatureInteropMockRecorder
	isgomock struct{}
}

// MockFetchFeatureInteropMockRecorder is the mock recorder for MockFetchFeatureInterop.
type MockFetchFeatureInteropMockRecorder struct {
	mock *MockFetchFeatureInterop
}

// NewMockFetchFeatureInterop creates a new mock instance.
func NewMockFetchFeatureInterop(ctrl *gomock.Controller) *MockFetchFeatureInterop {
	mock := &MockFetchFeatureInterop{ctrl: ctrl}
	mock.recorder = &MockFetchFeatureInteropMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchFeatureInterop) EXPECT() *MockFetchFeatureInteropMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockFetchFeatureInterop) Fetch(ctx context.Context, isExperimental bool) ([][]string, [][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, isExperimental)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].([][]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Fetch indicates an expected call of Fetch.
func (mr *MockFetchFeatureInteropMockRecorder) Fetch(ctx, isExperimental any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockFetchFeatureInterop)(nil).Fetch), ctx, isExperimental)
}
