// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/web-platform-tests/wpt.fyi/shared (interfaces: GitHubOAuth,GitHubAccessControl)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -destination sharedtest/github_oauth_mock.go -package sharedtest github.com/web-platform-tests/wpt.fyi/shared GitHubOAuth,GitHubAccessControl
//

// Package sharedtest is a generated GoMock package.
package sharedtest

import (
	context "context"
	reflect "reflect"

	github "github.com/google/go-github/v80/github"
	shared "github.com/web-platform-tests/wpt.fyi/shared"
	gomock "go.uber.org/mock/gomock"
	oauth2 "golang.org/x/oauth2"
)

// MockGitHubOAuth is a mock of GitHubOAuth interface.
type MockGitHubOAuth struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubOAuthMockRecorder
	isgomock struct{}
}

// MockGitHubOAuthMockRecorder is the mock recorder for MockGitHubOAuth.
type MockGitHubOAuthMockRecorder struct {
	mock *MockGitHubOAuth
}

// NewMockGitHubOAuth creates a new mock instance.
func NewMockGitHubOAuth(ctrl *gomock.Controller) *MockGitHubOAuth {
	mock := &MockGitHubOAuth{ctrl: ctrl}
	mock.recorder = &MockGitHubOAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubOAuth) EXPECT() *MockGitHubOAuthMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockGitHubOAuth) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockGitHubOAuthMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockGitHubOAuth)(nil).Context))
}

// Datastore mocks base method.
func (m *MockGitHubOAuth) Datastore() shared.Datastore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Datastore")
	ret0, _ := ret[0].(shared.Datastore)
	return ret0
}

// Datastore indicates an expected call of Datastore.
func (mr *MockGitHubOAuthMockRecorder) Datastore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Datastore", reflect.TypeOf((*MockGitHubOAuth)(nil).Datastore))
}

// GetAccessToken mocks base method.
func (m *MockGitHubOAuth) GetAccessToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockGitHubOAuthMockRecorder) GetAccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockGitHubOAuth)(nil).GetAccessToken))
}

// GetAuthCodeURL mocks base method.
func (m *MockGitHubOAuth) GetAuthCodeURL(state string, opts ...oauth2.AuthCodeOption) string {
	m.ctrl.T.Helper()
	varargs := []any{state}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAuthCodeURL", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthCodeURL indicates an expected call of GetAuthCodeURL.
func (mr *MockGitHubOAuthMockRecorder) GetAuthCodeURL(state any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{state}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthCodeURL", reflect.TypeOf((*MockGitHubOAuth)(nil).GetAuthCodeURL), varargs...)
}

// GetUser mocks base method.
func (m *MockGitHubOAuth) GetUser(client *github.Client) (*github.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", client)
	ret0, _ := ret[0].(*github.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockGitHubOAuthMockRecorder) GetUser(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockGitHubOAuth)(nil).GetUser), client)
}

// NewClient mocks base method.
func (m *MockGitHubOAuth) NewClient(oauthCode string) (*github.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", oauthCode)
	ret0, _ := ret[0].(*github.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClient indicates an expected call of NewClient.
func (mr *MockGitHubOAuthMockRecorder) NewClient(oauthCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockGitHubOAuth)(nil).NewClient), oauthCode)
}

// SetRedirectURL mocks base method.
func (m *MockGitHubOAuth) SetRedirectURL(url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRedirectURL", url)
}

// SetRedirectURL indicates an expected call of SetRedirectURL.
func (mr *MockGitHubOAuthMockRecorder) SetRedirectURL(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRedirectURL", reflect.TypeOf((*MockGitHubOAuth)(nil).SetRedirectURL), url)
}

// MockGitHubAccessControl is a mock of GitHubAccessControl interface.
type MockGitHubAccessControl struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubAccessControlMockRecorder
	isgomock struct{}
}

// MockGitHubAccessControlMockRecorder is the mock recorder for MockGitHubAccessControl.
type MockGitHubAccessControlMockRecorder struct {
	mock *MockGitHubAccessControl
}

// NewMockGitHubAccessControl creates a new mock instance.
func NewMockGitHubAccessControl(ctrl *gomock.Controller) *MockGitHubAccessControl {
	mock := &MockGitHubAccessControl{ctrl: ctrl}
	mock.recorder = &MockGitHubAccessControlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubAccessControl) EXPECT() *MockGitHubAccessControlMockRecorder {
	return m.recorder
}

// IsValidAdmin mocks base method.
func (m *MockGitHubAccessControl) IsValidAdmin() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidAdmin")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidAdmin indicates an expected call of IsValidAdmin.
func (mr *MockGitHubAccessControlMockRecorder) IsValidAdmin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidAdmin", reflect.TypeOf((*MockGitHubAccessControl)(nil).IsValidAdmin))
}

// IsValidWPTMember mocks base method.
func (m *MockGitHubAccessControl) IsValidWPTMember() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidWPTMember")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidWPTMember indicates an expected call of IsValidWPTMember.
func (mr *MockGitHubAccessControlMockRecorder) IsValidWPTMember() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidWPTMember", reflect.TypeOf((*MockGitHubAccessControl)(nil).IsValidWPTMember))
}
