// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/web-platform-tests/wpt.fyi/shared (interfaces: DiffAPI)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -destination sharedtest/run_diff_mock.go -package sharedtest github.com/web-platform-tests/wpt.fyi/shared DiffAPI
//

// Package sharedtest is a generated GoMock package.
package sharedtest

import (
	url "net/url"
	reflect "reflect"

	mapset "github.com/deckarep/golang-set"
	shared "github.com/web-platform-tests/wpt.fyi/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockDiffAPI is a mock of DiffAPI interface.
type MockDiffAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDiffAPIMockRecorder
	isgomock struct{}
}

// MockDiffAPIMockRecorder is the mock recorder for MockDiffAPI.
type MockDiffAPIMockRecorder struct {
	mock *MockDiffAPI
}

// NewMockDiffAPI creates a new mock instance.
func NewMockDiffAPI(ctrl *gomock.Controller) *MockDiffAPI {
	mock := &MockDiffAPI{ctrl: ctrl}
	mock.recorder = &MockDiffAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiffAPI) EXPECT() *MockDiffAPIMockRecorder {
	return m.recorder
}

// GetDiffURL mocks base method.
func (m *MockDiffAPI) GetDiffURL(before, after shared.TestRun, diffFilter *shared.DiffFilterParam) *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiffURL", before, after, diffFilter)
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// GetDiffURL indicates an expected call of GetDiffURL.
func (mr *MockDiffAPIMockRecorder) GetDiffURL(before, after, diffFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiffURL", reflect.TypeOf((*MockDiffAPI)(nil).GetDiffURL), before, after, diffFilter)
}

// GetMasterDiffURL mocks base method.
func (m *MockDiffAPI) GetMasterDiffURL(testRun shared.TestRun, diffFilter *shared.DiffFilterParam) *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterDiffURL", testRun, diffFilter)
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// GetMasterDiffURL indicates an expected call of GetMasterDiffURL.
func (mr *MockDiffAPIMockRecorder) GetMasterDiffURL(testRun, diffFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterDiffURL", reflect.TypeOf((*MockDiffAPI)(nil).GetMasterDiffURL), testRun, diffFilter)
}

// GetRunsDiff mocks base method.
func (m *MockDiffAPI) GetRunsDiff(before, after shared.TestRun, filter shared.DiffFilterParam, paths mapset.Set) (shared.RunDiff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunsDiff", before, after, filter, paths)
	ret0, _ := ret[0].(shared.RunDiff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunsDiff indicates an expected call of GetRunsDiff.
func (mr *MockDiffAPIMockRecorder) GetRunsDiff(before, after, filter, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunsDiff", reflect.TypeOf((*MockDiffAPI)(nil).GetRunsDiff), before, after, filter, paths)
}
