// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/web-platform-tests/wpt.fyi/shared (interfaces: TriageMetadataInterface)

// Package sharedtest is a generated GoMock package.
package sharedtest

import (
	gomock "github.com/golang/mock/gomock"
	shared "github.com/web-platform-tests/wpt.fyi/shared"
	reflect "reflect"
)

// MockTriageMetadataInterface is a mock of TriageMetadataInterface interface
type MockTriageMetadataInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTriageMetadataInterfaceMockRecorder
}

// MockTriageMetadataInterfaceMockRecorder is the mock recorder for MockTriageMetadataInterface
type MockTriageMetadataInterfaceMockRecorder struct {
	mock *MockTriageMetadataInterface
}

// NewMockTriageMetadataInterface creates a new mock instance
func NewMockTriageMetadataInterface(ctrl *gomock.Controller) *MockTriageMetadataInterface {
	mock := &MockTriageMetadataInterface{ctrl: ctrl}
	mock.recorder = &MockTriageMetadataInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTriageMetadataInterface) EXPECT() *MockTriageMetadataInterfaceMockRecorder {
	return m.recorder
}

// Triage mocks base method
func (m *MockTriageMetadataInterface) Triage(arg0 shared.MetadataResults) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Triage", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Triage indicates an expected call of Triage
func (mr *MockTriageMetadataInterfaceMockRecorder) Triage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Triage", reflect.TypeOf((*MockTriageMetadataInterface)(nil).Triage), arg0)
}
