runtime: custom
env: flex
service: spannerwrite

# Should match something at https://cloud.google.com/compute/docs/machine-types.
resources:
  # g1-small
  cpu: 0.5
  memory_gb: 1.70

# Setting values under automatic_scaling yields error:
# (gcloud.app.deploy) INVALID_ARGUMENT: VM-based automatic scaling should NOT have the following parameter(s): [auto_scaling parameter name]
#
# According to https://stackoverflow.com/questions/35416319/how-to-set-automatic-scaling-in-google-cloud-managed-vm
# automatic_scaling should be on by default with no explicit configuration.
#
# automatic_scaling:
#   ...

liveness_check:
  path: "/_ah/liveness_check"

readiness_check:
  path: "/_ah/readiness_check"
