[tox]
envlist = py311
skipsdist=True

[testenv]
download=True
deps =
    google-cloud-ndb
    google-cloud-storage
    requests
commands =
    python -m unittest discover -s {toxinidir} -p "*_test.py"
