// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/web-platform-tests/wpt.fyi/api/azure (interfaces: API)

// Package azure is a generated GoMock package.
package azure

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	github "github.com/google/go-github/github"
)

// MockAPI is a mock of API interface
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// FetchAzureArtifact mocks base method
func (m *MockAPI) FetchAzureArtifact(arg0 BuildArtifact, arg1 io.Writer) error {
	ret := m.ctrl.Call(m, "FetchAzureArtifact", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchAzureArtifact indicates an expected call of FetchAzureArtifact
func (mr *MockAPIMockRecorder) FetchAzureArtifact(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAzureArtifact", reflect.TypeOf((*MockAPI)(nil).FetchAzureArtifact), arg0, arg1)
}

// GetAzureArtifactsURL mocks base method
func (m *MockAPI) GetAzureArtifactsURL(arg0, arg1 string, arg2 int64) string {
	ret := m.ctrl.Call(m, "GetAzureArtifactsURL", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAzureArtifactsURL indicates an expected call of GetAzureArtifactsURL
func (mr *MockAPIMockRecorder) GetAzureArtifactsURL(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAzureArtifactsURL", reflect.TypeOf((*MockAPI)(nil).GetAzureArtifactsURL), arg0, arg1, arg2)
}

// HandleCheckRunEvent mocks base method
func (m *MockAPI) HandleCheckRunEvent(arg0 *github.CheckRunEvent) (bool, error) {
	ret := m.ctrl.Call(m, "HandleCheckRunEvent", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleCheckRunEvent indicates an expected call of HandleCheckRunEvent
func (mr *MockAPIMockRecorder) HandleCheckRunEvent(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCheckRunEvent", reflect.TypeOf((*MockAPI)(nil).HandleCheckRunEvent), arg0)
}
