// Code generated by MockGen. DO NOT EDIT.
// Source: api/azure/api.go

// Package azure is a generated GoMock package.
package azure

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	github "github.com/google/go-github/github"
)

// MockAPI is a mock of API interface
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// HandleCheckRunEvent mocks base method
func (m *MockAPI) HandleCheckRunEvent(arg0 *github.CheckRunEvent) (bool, error) {
	ret := m.ctrl.Call(m, "HandleCheckRunEvent", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleCheckRunEvent indicates an expected call of HandleCheckRunEvent
func (mr *MockAPIMockRecorder) HandleCheckRunEvent(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCheckRunEvent", reflect.TypeOf((*MockAPI)(nil).HandleCheckRunEvent), arg0)
}

// GetAzureArtifactsURL mocks base method
func (m *MockAPI) GetAzureArtifactsURL(owner, repo string, buildID int64) string {
	ret := m.ctrl.Call(m, "GetAzureArtifactsURL", owner, repo, buildID)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAzureArtifactsURL indicates an expected call of GetAzureArtifactsURL
func (mr *MockAPIMockRecorder) GetAzureArtifactsURL(owner, repo, buildID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAzureArtifactsURL", reflect.TypeOf((*MockAPI)(nil).GetAzureArtifactsURL), owner, repo, buildID)
}

// FetchAzureArtifact mocks base method
func (m *MockAPI) FetchAzureArtifact(arg0 BuildArtifact) ([]byte, error) {
	ret := m.ctrl.Call(m, "FetchAzureArtifact", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAzureArtifact indicates an expected call of FetchAzureArtifact
func (mr *MockAPIMockRecorder) FetchAzureArtifact(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAzureArtifact", reflect.TypeOf((*MockAPI)(nil).FetchAzureArtifact), arg0)
}
