# Copyright 2017 The WPT Dashboard Project. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

runtime: go
api_version: go1
instance_class: F4_1G

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
  # Couple of special-case dynamic components.
- url: /components/wpt-env-flags.js
  script: _go_app
  secure: always
- url: /components
  static_dir: components
  secure: always
- url: /static
  static_dir: static
  expiration: "1d"
  secure: always
- url: /service-worker-installer.js
  static_files: service-worker-installer.js
  upload: service-worker-installer.js
  secure: always
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always
- url: /.*
  script: _go_app
  secure: always

# Don't upload mock-data static files to AppEngine
skip_files:
- components/test/
- static/b952881825/
- static/wptd-metrics/
- test/
- .eslintrc.json
- package.json
- README.md
- .*/artifact_test.zip
